function verify_hex(hex)
    if not hex.hasTag('Hex') then
        local msg = "The highlighted hex is missing the 'Hex' tag. Please ensure "..
            "that all newly added hexes are tagged 'Hex' and have the appropriate " ..
            "variables (VP, discovery, etc) added to their scripts. See other " ..
            "hexes for reference."
        alert(msg, hex)
        return false
    end

    if hex.getVar('reputation') == nil then
        local msg = "The highlighted hex is missing scripted reputation information (and " ..
        "possibly other scripted info). Please ensure " ..
        "that all newly added hexes are tagged 'Hex' and have the appropriate " ..
        "variables (VP, discovery, etc) added to their scripts. See other " ..
        "hexes for reference."
        alert(msg, hex)
        return false
    end
end
