function verify_hex(hex)
    assert(hex.hasTag('Hex'), "A hex is missing the 'Hex' tag. Please ensure "..
        "that all newly added hexes are tagged 'Hex' and have the appropriate " ..
        "variables (VP, discovery, etc) added to their scripts. See other " ..
        "hexes for reference.")

    assert(hex.getVar('reputation')~=nil,
        "A hex is missing scripted reputation information (and possibly other "..
        "scripted info). Please ensure " ..
        "that all newly added hexes are tagged 'Hex' and have the appropriate " ..
        "variables (VP, discovery, etc) added to their scripts. See other " ..
        "hexes for reference.")
        
end
