function verify_influence_disc(disc)

    if not disc.hasTag('Influence') then
        local msg = "The highlighted disc is missing the 'Influence' tag. Please " ..
            "ensure that all influence discs are tagged 'Influence'. See " ..
            "other influence discs for reference."
        alert(msg, disc)
        return false
    end

    local c = disc.getColorTint()
    c = c:toString()
    if c == nil then
        local msg = "The highlighted disc is colored incorrectly. All influence " ..
            "discs should be colored exactly their owner's color. Coloring " ..
            "a disc any other color will affect the script."
        alert(msg, disc)
        return false
    end

    return true
end

function verify_number_of_influence_on_hex(hex, discs)
    if #discs > 1 then
        broadcastToAll('Error getting the owner of hex ('..
            tostring(hex.getVar('number')) .. ')\n' ..
            'There are multiple influence discs on the hex!', Color.Yellow)
        hex.highlightOn(Color.Orange, 15)
        return false
    end
    return true
end
